# Configure variables for this example and build using generic makefile

APP_NAME           = HDevelopTemplate
APP_FORM           = HDevelopTemplate
XL                 = 0
ENGINE             = 0

!include make.dotnet.win
