# Configure variables for this example and build using generic makefile

APP_NAME           = MultiThreading
APP_FORM           = MultiThreadingForm
XL                 = 0
ENGINE             = 0

!include make.dotnet.win
